[settings]
provider = "native"

[relaychain]
chain           = "rococo-local"
default_args    = ["--database=paritydb", "-lparachain=debug"]
default_command = "tmp/polkadot"

[[relaychain.nodes]]
name      = "alice"
validator = true
[[relaychain.nodes]]
name      = "bob"
validator = true

[[parachains]]
chain           = "koi-genesis"
force_decorator = "generic-evm"
id              = 2105
[[parachains.collators]]
args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
command  = "tmp/darwinia"
name     = "c1"
rpc_port = 10000
[[parachains.collators]]
args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
command  = "tmp/darwinia"
name     = "c2"
rpc_port = 10001
[[parachains.collators]]
args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
command  = "tmp/darwinia"
name     = "c3"
rpc_port = 10002
