[config]
default_to_workspace = false
# skip_core_tasks      = true
# skip_git_env_info    = true
# skip_rust_env_info   = true
# skip_crate_env_info  = true

[env]
CHAIN             = "all"
NODE_COMPILE_ARGS = "--locked -p darwinia --features"

# Checks.

[tasks.fmt]
toolchain = "nightly"
command   = "cargo"
args      = ["fmt"]

[tasks.clippy]
env     = { "SKIP_WASM_BUILD" = "1" }
command = "cargo"
args    = ["clippy"]

[tasks.c]
alias = "clippy"

# Build nodes.

[tasks.build-node]
command = "cargo"
args    = [
	"build",
	"@@split(NODE_COMPILE_ARGS, )",
	"${CHAIN}-runtime",
	"@@split(EXTRA_ARGS, )",
]

[tasks.bn]
alias = "build-node"

[tasks.build-koi]
extend = "build-node"
env    = { "CHAIN" = "koi" }

[tasks.bk]
alias = "build-koi"

[tasks.build-crab]
extend = "build-node"
env    = { "CHAIN" = "crab" }

[tasks.bc]
alias = "build-crab"

[tasks.build-darwinia]
extend = "build-node"
env    = { "CHAIN" = "darwinia" }

[tasks.bd]
alias = "build-darwinia"

# Build release nodes.

[tasks.build-release-node]
extend = "build-node"
env    = { "EXTRA_ARGS" = "-r" }

[tasks.brn]
alias = "build-release-node"

[tasks.build-release-koi]
extend = "build-node"
env    = { "CHAIN" = "koi", EXTRA_ARGS = "-r" }

[tasks.brk]
alias = "build-release-koi"

[tasks.build-release-crab]
extend = "build-node"
env    = { "CHAIN" = "crab", EXTRA_ARGS = "-r" }

[tasks.brc]
alias = "build-release-crab"

[tasks.build-release-darwinia]
extend = "build-node"
env    = { "CHAIN" = "darwinia", EXTRA_ARGS = "-r" }

[tasks.brd]
alias = "build-release-darwinia"

# Build benchmark nodes.

[tasks.build-benchmark]
extend = "build-node"
env    = { "EXTRA_ARGS" = "--features runtime-benchmarks -r" }

[tasks.bb]
alias = "build-benchmark"

[tasks.build-benchmark-koi]
extend = "build-node"
env    = { "CHAIN" = "koi", "EXTRA_ARGS" = "--features runtime-benchmarks -r" }

[tasks.bbk]
alias = "build-benchmark-koi"

[tasks.build-benchmark-crab]
extend = "build-node"
env    = { "CHAIN" = "crab", "EXTRA_ARGS" = "--features runtime-benchmarks -r" }

[tasks.bbc]
alias = "build-benchmark-crab"

[tasks.build-benchmark-darwinia]
extend = "build-node"
env    = { "CHAIN" = "darwinia", "EXTRA_ARGS" = "--features runtime-benchmarks -r" }

[tasks.bbd]
alias = "build-benchmark-darwinia"

# Run dev nodes.

# This can not be used directly, as it requires a chain to be specified.
[tasks.run-dev]
command = "cargo"
args    = [
	"run",
	"@@split(NODE_COMPILE_ARGS, )",
	"${CHAIN}-runtime",
	"@@split(EXTRA_ARGS, )",
	"--",
	"--unsafe-rpc-external",
	"--tmp",
	"--rpc-cors",
	"all",
	"--rpc-methods",
	"unsafe",
	"--alice",
	"--collator",
	"--chain",
	"${CHAIN}-dev"
]

[tasks.run-dev-koi]
extend = "run-dev"
env    = { "CHAIN" = "koi" }

[tasks.rdk]
alias = "run-dev-koi"

[tasks.run-dev-crab]
extend = "run-dev"
env    = { "CHAIN" = "crab" }

[tasks.rdc]
alias = "run-dev-crab"

[tasks.run-dev-darwinia]
extend = "run-dev"
env    = { "CHAIN" = "darwinia" }

[tasks.rdd]
alias = "run-dev-darwinia"

# Run release dev nodes.

# This can not be used directly, as it requires a chain to be specified.
[tasks.run-release]
extend = "run-dev"
env    = { "EXTRA_ARGS" = "-r" }

[tasks.run-release-dev-koi]
extend = "run-dev"
env    = { "CHAIN" = "koi", "EXTRA_ARGS" = "-r" }

[tasks.rrdk]
alias = "run-release-dev-koi"

[tasks.run-release-dev-crab]
extend = "run-dev"
env    = { "CHAIN" = "crab", "EXTRA_ARGS" = "-r" }

[tasks.rrdc]
alias = "run-release-dev-crab"

[tasks.run-release-dev-darwinia]
extend = "run-dev"
env    = { "CHAIN" = "darwinia", "EXTRA_ARGS" = "-r" }

[tasks.rrdd]
alias = "run-release-dev-darwinia"

# Run benchmark nodes.

# This can not be used directly, as it requires a chain to be specified.
[tasks.run-benchmark]
command = "cargo"
args    = [
	"run",
	"@@split(NODE_COMPILE_ARGS, )",
	"${CHAIN}-runtime",
	"--features",
	"runtime-benchmarks",
	"-r",
	"--",
	"benchmark",
	"pallet",
	"--header",
	".maintain/license-header",
	"--heap-pages",
	"4096",
	"--chain",
	"${CHAIN}-dev",
	"--output",
	"runtime/${CHAIN}/src/weights",
	"--pallet",
	"*",
	"--extrinsic",
	"*",
	"--steps",
	"50",
	"--repeat",
	"20"
]

[tasks.run-benchmark-koi]
extend = "run-benchmark"
env    = { "CHAIN" = "koi" }

[tasks.rbk]
alias = "run-benchmark-koi"

[tasks.run-benchmark-crab]
extend = "run-benchmark"
env    = { "CHAIN" = "crab" }

[tasks.rbc]
alias = "run-benchmark-crab"

[tasks.run-benchmark-darwinia]
extend = "run-benchmark"
env    = { "CHAIN" = "darwinia" }

[tasks.rbd]
alias = "run-benchmark-darwinia"
