FROM centos:7

# only for centos-7

# change mirrorlist
RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && yum makecache \
	# update
	yum -y update && yum -y upgrade && yum -y install \
	# tool
	git make \
	# compiler
	clang gcc gcc-c++ llvm
