FROM debian:stable-slim
RUN apt-get update && apt-get install -y --no-install-recommends openssl && rm -rf /var/lib/apt/lists/*
COPY bin/darwinia_x86_64-linux-gnu /usr/local/bin/darwinia
ENTRYPOINT [ "/usr/local/bin/darwinia" ]
