FROM rustembedded/cross:aarch64-unknown-linux-gnu

# only for aarch64

# change mirrorlist
RUN curl https://raw.githubusercontent.com/oooldking/script/master/superupdate.sh | bash && \
	# update
	apt update && apt upgrade -y && apt install -y \
	# lib
	libc6-dev-i386 \
	# compiler
	gcc-aarch64-linux-gnu gcc-5-aarch64-linux-gnu g++-aarch64-linux-gnu g++-5-aarch64-linux-gnu \
	clang llvm libclang-dev
