# This file is part of Darwinia.
#
# Copyright (C) 2018-2021 Darwinia Network
# SPDX-License-Identifier: GPL-3.0
#
# Darwinia is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Darwinia is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Darwinia. If not, see <https://www.gnu.org/licenses/>.

FROM rustembedded/cross:armv7-unknown-linux-gnueabihf

# only for armv7

# change mirrorlist
RUN curl https://raw.githubusercontent.com/oooldking/script/master/superupdate.sh | bash && \
	# update
	apt update && apt upgrade -y && apt install -y \
	# lib
	libc6-dev-i386 \
	# compiler
	gcc-arm-linux-gnueabihf gcc-5-arm-linux-gnueabihf g++-arm-linux-gnueabihf g++-5-arm-linux-gnueabihf \
	clang llvm libclang-dev
