#!/bin/sh

export PATH=$PATH:$HOME/.cargo/bin

rustfmt --version &>/dev/null
if [ $? != 0 ]; then
	printf "[pre_commit] [ERROR] \"rustfmt\" not available. \n"
	printf "[pre_commit] [ERROR] rustfmt can be installed via - \n"
	printf "[pre_commit] $ rustup component add rustfmt \n"
	exit 1
fi


problem_files=()

# first collect all the files that need reformatting
for file in $(git diff --name-only --cached); do
    if [ ${file: -3} == ".rs" ]; then
        rustfmt --check $file 
        if [ $? != 0 ]; then
            problem_files+=($file)
        fi
    fi
done

if [ ${#problem_files[@]} != 0 ]; then
  printf "[pre_commit] [ERROR] Plaese format the files via -\n"
  printf "[pre_commit] $ cargo fmt --all \n"
  printf "[pre_commit] [ERROR] If you want to keep your format with special reason, \n"
  printf "[pre_commit] [ERROR] you can use this macro. \n"
  printf "[pre_commit] #[rustfmt::skip] \n"
  exit 1
fi

printf "[pre_commit] [SUCCESS] rustfmt ok \n"

exit 0
