name: Notify release
env:
  GITHUB_TOKEN: ${{ secrets.GH_TKN_DARWINIA }}

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  notify-mainnet:
    name: Notify mainnet
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: |
          TAG=$(echo ${{ github.ref }} | sed 's!.*/\(.*\)!\1!')
          gh workflow run wasm.yml --repo darwinia-network/darwinia-release -f network=mainnet -f tag=${TAG}
