name: Try Runtime

permissions:
  contents: read
  # Necessary to comment on the pull requests.
  pull-requests: write

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_TERM_COLOR: always

  RUST_BACKTRACE: full

on:
  issue_comment:
    types: [created]

jobs:
  try-runtime:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/bot try-runtime')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add the runtime name and URI here.
        runtime:
          - name: darwinia-runtime
            uri: wss://rpc.darwinia.network
          - name: crab-runtime
            uri: ws://g1.crab2.darwinia.network:9944
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Try-Runtime
        # It is recommended to use a specific version of the action in production.
        #
        # For example:
        # uses: hack-ink/polkadot-runtime-releaser/action/try-runtime@vX.Y.Z
        uses: hack-ink/polkadot-runtime-releaser/action/try-runtime@v0.2.0
        with:
          # The target runtime to build.
          #
          # For example, `polkadot-runtime` or `staging-kusama-runtime`.
          runtime: ${{ matrix.runtime.name }}
          # The features to enable for this try-runtime build.
          features: try-runtime
          # Rust toolchain version to build the runtime.
          toolchain-ver: 1.82.0
          # Try-Runtime CLI version.
          try-runtime-ver: 0.8.0
          # Whether to skip enforcing that the new runtime `spec_version` is greater or equal to the existing `spec_version`.
          disable-spec-version-check: ${{ contains(github.event.comment.body, '--disable-spec-version-check') }}
          # Whether to disable migration idempotency checks.
          disable-idempotency-checks: ${{ contains(github.event.comment.body, '--disable-idempotency-checks') }}
          # The URI of the node to connect to fetch the state.
          uri: ${{ matrix.runtime.uri }}
