name: Try Runtime

permissions:
  contents: read
  # Necessary to comment on the pull requests.
  pull-requests: write

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_TERM_COLOR: always

  RUST_BACKTRACE: full

on:
  issue_comment:
    types: [created]

jobs:
  try-runtime:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/bot try-runtime')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add the runtime name and URI here.
        runtime:
          - name: darwinia-runtime
            uri: wss://rpc.darwinia.network
          - name: crab-runtime
            uri: ws://g1.crab2.darwinia.network:9944
    steps:
      - name: Load pull request metadata
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            core.setOutput('is_fork', pr.head.repo.fork ? 'true' : 'false');
            core.setOutput('head_sha', pr.head.sha);
            core.setOutput('head_repo', pr.head.repo.full_name);
      - name: Skip fork pull requests
        if: steps.pr.outputs.is_fork == 'true'
        run: |
          echo "Skipping try-runtime for forked pull requests."
          exit 0
      - name: Fetch latest code
        if: steps.pr.outputs.is_fork == 'false'
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr.outputs.head_repo }}
          ref: ${{ steps.pr.outputs.head_sha }}
      - name: Try-Runtime
        if: steps.pr.outputs.is_fork == 'false'
        # It is recommended to use a specific version of the action in production.
        #
        # For example:
        # uses: hack-ink/polkadot-runtime-releaser/action/try-runtime@vX.Y.Z
        uses: hack-ink/polkadot-runtime-releaser/action/try-runtime@v0.2.0
        with:
          # The target runtime to build.
          #
          # For example, `polkadot-runtime` or `staging-kusama-runtime`.
          runtime: ${{ matrix.runtime.name }}
          # The features to enable for this try-runtime build.
          features: try-runtime
          # Rust toolchain version to build the runtime.
          toolchain-ver: 1.82.0
          # Try-Runtime CLI version.
          try-runtime-ver: 0.8.0
          # Whether to skip enforcing that the new runtime `spec_version` is greater or equal to the existing `spec_version`.
          disable-spec-version-check: ${{ contains(github.event.comment.body, '--disable-spec-version-check') }}
          # Whether to disable migration idempotency checks.
          disable-idempotency-checks: ${{ contains(github.event.comment.body, '--disable-idempotency-checks') }}
          # The URI of the node to connect to fetch the state.
          uri: ${{ matrix.runtime.uri }}
